spring:
  datasource:
    url: jdbc:mysql://localhost:3306/managebook2
    username: root
    password: new-strong-password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  servlet:
    context-path: '/api'
  port: 8080
logging:
  level:
    org:
      springframework: info
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%3p}) %clr(-){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"